### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by ddddxxx** [SwiftGen/SwiftGenKit#47]

**Comment by djbe** [comment]
Neither @AliSoftware nor myself use Carthage, and we don't directly see the need for it, especially because it is an extra publishing method we'll need to maintain.

If you'd like this feature, you're welcome to implement it and open a PR 😄

**Comment by AliSoftware** [comment]
How is SwiftGenKit not already Carthage-compatible?! I though having an xcodeproj building the framework was enough

**Comment by ddddxxx** [comment]
@AliSoftware The xcodeproj in top level is just for test. The actual xcodeproj building the framework is in subdirectory. which Carthage cannot recognize.

**Comment by AliSoftware** [comment]
Ah. This will change soon when we implement SwiftGen/SwiftGen#326 anyway.
SPM support will be a priority so the structuring of the repo hierarchy will be driven by SPM, not by Carthage. But from there you can use SPM commands to generate the xcodeproj needed by Carthage (and I suppose at some point Carthage will support building projects using SPM anyway, they'll have to since it's gonna be the new standard on Apple projects)

**Comment by djbe** [comment]
Closing in favour of https://github.com/SwiftGen/SwiftGen/issues/368.
