### ISSUE TITLE
Mixing storyboards with and without trait variations.

### ISSUE THREAD

**Issue by traffer** [SwiftGen/SwiftGenKit#58]
StoryboardParser does not assume storyboards to have the same target runtime if the storyboards differ by trait variations option, i.e. "Use Trait Variations" option is on for some storyboard(-s), for others - off.
When trait variations is off for a storyboard, "targetRuntime" attribute becomes specific, for instance, targetRuntime="iOS.CocoaTouch.iPad".
As the result, SwiftGen generates a file with a single message "Mixed AppKit and UIKit storyboard files found, please invoke swiftgen with these separately", while the runtime is still "iOS.CocoaTouch" but for a specific device.

**Comment by AliSoftware** [comment]
Oh, that's a very good point. We'll look into this soon, thanks for reporting the issue!

Open question though, I wonder how that would go if you have multiple storyboards for the same screen and with the same sceneIdentifiers, one for iPad and another for iPhone for example.
The constants generated by Swiftgen will risk to clash if multiple scenes parsed by SwiftGen from those different files have the same identifier — even if at runtime only one of the two will be used depending on the device. I wonder how we should address that… any suggestion welcome

**Comment by djbe** [comment]
Uhm, last time I used trait variations, it's more of a "enabling/disabling" views, constraints and properties for each trait. Not different scenes/segues.

No idea if that's possible now, worth investigating.

**Comment by traffer** [comment]
Well, it should not be an issue in my case as I'm developing a fullscreen ipad app where using trait variations makes not much sense, and I ran into the issue just because of early development stage when there are a lot of quick'n'dirty things in project.

Is it possible to catch the described issue, and put appropriate message into the generated file instead of "Mixed AppKit and UIKit storyboard files found ..."? At least, this would save developer time, and give a hint on what went wrong with his/her storyboards from Swiftgen point of view.

@AliSoftware ,
I'm not sure I understand which issue you see in the case when there are multiple storyboards for the same screen and with the same sceneIdentifiers, one for iPad and another for iPhone, because, technically, it will be different storyboard files, and (correct me plz if i'm wrong) StoryboardScene namespace will/should contain separate definitions for each file.
For instance, you have "Landing" screen, and decided to split the user interface into 2 different storyboards, let's say, "landing_iphone.storyboard" and "landing_ipad.storyboard". Each of them has "Main" scene, and both have no trait variations. I suppose, the enum will look like 
```
enum StoryboardScene {
    enum landing_iphone: StoryboardType {
        static let main = SceneType<LandingViewController>(storyboard: landing_iphone.self, identifier: "Main")
    }
    enum landing_ipad: StoryboardType {
        static let main = SceneType<LandingViewController>(storyboard: landing_ipad.self, identifier: "Main")
    }
}
```

**Comment by AliSoftware** [comment]
@traffer You're almost right, except that if you use different storyboard files for iPhone and iPad, you'll likely use the official naming variation for each, i.e. `Landing.storyboard` and `Landing~ipad.storyboard`.

This naming convention isn't that much used nowadays since Apple pushes towards using a unique storyboard file for both iPhone and iPad — and use Size Classes to handle variations between the different screen size categories — but it still works. And when you respect that `~ipad` convention, that means that the name to use when referencing that storyboard by code is still `Landing`. Meaning that `UIStoryboard(named: "Landing")` would automatically load `Landing.storyboard` on iPhone but `Landing~ipad.storyboard` on iPad.  
So they would have the same, official common name in code, and would have to lead to the same `enum landing: StoryboardType` enum being generated (tbh I don't think we handle this `~ipad` special naming case in SwiftGen today, given how this naming convention is outdated and we probably forgot to handle it specially, but if you were to use this naming convention that's what you'd probably expect to have), so that in your code you wouldn't have to test if you're on iPhone or iPad to know which Storyboard to load, you'd load "the storyboard named Landing" and the runtime will automatically load the proper one depending on the device.

Once again, that way of doing things (having multiple storyboards for the same screens, but one for iPhone and one for iPad, and using the official `~ipad` suffix for the iPad variation) is outdated and deprecated by Apple since a while now.

What I don't get if you don't use that "multiple files with naming convention" technique but just activated the "Size Classes" variation in your storyboard, is why the target would change to `iOS.CocoaTouch.iPad` then, since Size Classes are not linked to a device like iPhone or iPad but to… size classes (Compact vs Regular) — meaning that an iPad mini could be considered Compact and an iPhone X in landscape could be considered Regular, unrelated to the device type itself.

Or maybe by "trait variations" you mean something else than what we mean by "size classes"?

**Comment by traffer** [comment]
@AliSoftware , let us put outdated things aside.

There is no "Use Size Classes" option in storyboards anymore. Now it is named "Use Trait Variations".
If you uncheck it, the target runtime will be either "iOS.CocoaTouch.iPad" or "iOS.CocoaTouch" depending on choice you made in "Disable Trait Variations" dialog. In my case, I chose to keep size class data for iPad only for one of storyboards I have in project (please see the 1st comment).

Is it possible to catch the described issue, and put appropriate message into the generated file instead of "Mixed AppKit and UIKit storyboard files found ..."?
At least, this would save developer time, and give a hint on what went wrong with his/her storyboards from Swiftgen point of view.

**Comment by AliSoftware** [comment]
Ah I see. I've probably missed that change of process between Xcode 7, 8 and 9 (I remember how at some point they introduced size classes, then all design in IB were on square views to visually enforce the abstraction of screen size, then lately they rolled back on having to choose iPhone or iPad for design when you opened an old storyboard to switch back from "square design" to "design with the proper view size/aspect ratio corresponding to what device you chose"… That's probably at that point that they introduced that variation and made the `targetName` change from `iOS.CocoaTouch` to `iOS.CocoaTouch.iPad`

We'll indeed have to patch SwiftGen to fix this and to either put an appropriate message instead of "Mixed AppKit and UIKit", or to even consider `iOS.CocoaTouch` and `iOS.CocoaTouch.iPad` to be equivalent and generate the proper constants directly, in case even when using mixed trait variations the constants would still make sense.

**Comment by djbe** [comment]
We only do full string matching here:
https://github.com/SwiftGen/SwiftGenKit/blob/master/Sources/Parsers/StoryboardParser.swift#L113
If we can't correctly map the target runtime, or there are differences, then the global platform variable will be `nil`:
https://github.com/SwiftGen/SwiftGenKit/blob/master/Sources/Parsers/StoryboardParser.swift#L144
Resulting in the templates outputting that error.

We can either add variations to the map, but that might not be maintainable long-term, or instead try to match using `hasPrefix`.

**Comment by AliSoftware** [comment]
I think `hasPrefix` will probably be good enough… be we'll have to experiment a bit with that to make sure we end up with something stable and sustainable long-term covering all possible use cases.

**Comment by djbe** [comment]
Definitely.

@traffer If you have a slimmed down version of your storyboard, that you'd be willing to share, that'd be great for testing purposes!

**Comment by djbe** [comment]
Closing in favour of https://github.com/SwiftGen/SwiftGen/issues/367.
